### PR TITLE
[Frontend][UST-281] fix notification

### LINKED ISSUE #595: Bug(frontend): notification center
**Describe the bug**
When the reputation is less than 0, there are endless notification notifying the user to checkin.

**To Reproduce**

1. create 2 users
2. report successfully to make one of them have negative reputation
3. check the notification center of that user

**Expected behavior**
Display only once or twice to inform the user.

**Screenshots**
https://drive.google.com/file/d/12MaiqhAW2uD6r5Bu8VzJJ_9PJUPN86J-/view?usp=sharing

### PR DESCRIPTION
**Pull request by UranusLin**
## Summary

This PR enhances the notification system by improving duplicate notification handling and adding comprehensive test coverage. The changes focus on making notification ID generation more consistent and robust while ensuring notifications are properly deduplicated across different notification types.

## Linked Issue

close #595 

## Impacted Areas

- `src/features/notification/stores/useNotificationStore.tsx`
- `src/features/notification/stores/useNotificationStore.test.tsx`

## Tests

Added comprehensive unit tests covering:
- Regular notification addition
- Duplicate notification prevention for daily notifications (LOW_REPUTATION type)
- Duplicate prevention for report adjudication notifications
- List and entities synchronization verification

To run the tests:
```bash
yarn run test src/features/notification/stores/useNotificationStore.test.tsx

### CODE REVIEW

File: packages/frontend/src/features/notification/stores/useNotificationStore.tsx [hunk 1]
```diff
@@ -26,34 +24,93 @@ const initialState: NotificationState = {
     clearNotificationDot: () => {},
 }
 
+const getNotificationId = (notification: NotificationData): string => {
+    switch (notification.type) {
+        case NotificationType.NEW_REPORT_ADJUDICATE:
+            return notification.link || notification.id
```
Comment (Xiawpohr) [inline packages/frontend/src/features/notification/stores/useNotificationStore.tsx:30]: NEW_REPORT_ADJUDICATE 的通知不會 link

File: packages/frontend/src/features/notification/stores/useNotificationStore.tsx [hunk 2]
```diff
@@ -26,34 +24,93 @@ const initialState: NotificationState = {
...
+        case NotificationType.LOW_REPUTATION:
+            return `${notification.type}_${new Date().toDateString()}`
```
Comment (Xiawpohr) [inline packages/frontend/src/features/notification/stores/useNotificationStore.tsx:32]: LOW_REPUTATION 的通知應該是要一天一次

File: packages/frontend/src/features/notification/stores/useNotificationStore.tsx [hunk 3]
```diff
@@ -26,34 +24,93 @@ const initialState: NotificationState = {
...
+                (n) =>
+                    n.type === NotificationType.LOW_REPUTATION &&
+                    new Date(n.time).toDateString() === today,
+            )
+        case NotificationType.NEW_REPORT_ADJUDICATE:
+            return notification.link ? notification.link in entities : false
+        default:
+            return false
+    }
+}
```
Comment (Xiawpohr) [inline packages/frontend/src/features/notification/stores/useNotificationStore.tsx:56]: 這個 function 跟 L78 的差異是什麼呢？

File: packages/frontend/src/features/notification/stores/useNotificationStore.tsx (hunk 1 above)
Comment (kittybest) [reply packages/frontend/src/features/notification/stores/useNotificationStore.tsx:30]: 截圖 2025-01-23 01 08 08

應該是因為沒有link，所以在底下L52判斷是否有重複的部分永遠是false，因此出現圖上的狀況

**Review by kittybest — APPROVED** [review]

File: packages/frontend/src/features/notification/stores/useNotificationStore.tsx (hunk 3 above)
Comment (UranusLin) [reply packages/frontend/src/features/notification/stores/useNotificationStore.tsx:61]: 已修正

File: .gitignore [hunk 4]
```diff
@@ -1,5 +1,7 @@
 node_modules/
 
+.idea
```
[the remark this answers is not in the document]
Comment (UranusLin) [reply .gitignore]: 這是JetBrains IDE 開啟時新增的資料夾，已移除

**Review by kittybest — APPROVED** [review]
lgtm now, thanks!
