### PR TITLE
[Fix]: Issue234 relay get post

### LINKED ISSUE #234: [Relay] get /api/post/:id will return 404
**Describe the bug**
點進`/post/:id`頁面後總是會出現default畫面，打開F12會看到
GET httpilocalhost800 PostDetail  tsx113 GD
簡單來說就是**找不到該post**
問題出在這⬇️
https://github.com/social-tw/social-tw-website/blob/3eacf2272e5fb27bbf8d4111dacceaf5ab79350d/packages/relay/src/services/PostService.ts#L235
這邊`postId`改成`_id`就可以了。

**To Reproduce**
- 註冊
- 發文
- 點擊貼文 ❗️

**Expected behavior**
應該要顯示正確的 1) 貼文內容 2) 評論內容 3) 投票結果

**Screenshots**

https://github.com/social-tw/social-tw-website/assets/9023842/128fab8a-682c-4084-a7a6-e2609e1c573a

**Desktop (please complete the following information):**

-   OS: [macOS]
-   Browser [chrome]

### PR DESCRIPTION
**Pull request by ryanycw**
## Summary

In this pull request, we adjust how we create posts to ensure all posts are on-chain before entering the database and only query post with postId. 

## Linked Issue

close #234 

## Details

We create posts by executing transactions. Return postId and transaction hash to the front.
```typescript
const { txHash, logs } = await TransactionManager.executeTransaction(
    appContract,
    APP_ADDRESS,
    calldata
)

const postId = logs
    .filter(
        (log): log is ethers.utils.LogDescription =>
            log !== null && log.name === 'Post'
    )
    .map((log) => log.args.postId)
    .find((postId) => postId !== undefined)
    .toString()

const epoch = Number(epochKeyProof.epoch)
const epochKey = epochKeyProof.epochKey.toString()

// after post data stored in DB, should add 1 to epoch key counter
await ActionCountManager.addActionCount(db, epochKey, epoch, (txDB) => {
    txDB.create('Post', {
        postId: postId,
        content: content,
        cid: cid.toString(),
        epochKey: epochKey,
        epoch: epoch,
        transactionHash: txHash,
        status: 1,
    })
    return 1
})

return { txHash, postId: postId }
```

## Impacted Areas

Mainly in the following area
- `packages/relay/src/routes/post.ts`
- `packages/relay/src/services/PostService.ts`
- `packages/relay/src/singletons/schema.ts`

## Verification Steps

```bash
yarn relay test
```

## Todo

-   [x] Refactor create a post using executeTx
-   [x] Refactor all codebase in relay using post._id to post.postId
-   [x] Refactor status in post schema to default 0

### CODE REVIEW

File: packages/relay/src/services/PostService.ts [hunk 1]
```diff
@@ -225,29 +228,47 @@ export class PostService {
...
+            )
+            .map((log) => log.args.postId)
+            .find((postId) => postId !== undefined)
+            .toString()
+
         const epoch = Number(epochKeyProof.epoch)
         const epochKey = epochKeyProof.epochKey.toString()
 
         // after post data stored in DB, should add 1 to epoch key counter
         await ActionCountManager.addActionCount(db, epochKey, epoch, (txDB) => {
```
Comment (Lisooo790926) [inline packages/relay/src/services/PostService.ts:259]: Maybe we should move add action counter to Synchronizer also, since these actions are atomic

File: packages/relay/src/services/singletons/TransactionManager.ts [hunk 2]
```diff
@@ -163,7 +164,7 @@ export class TransactionManager {
                     (log: ethers.utils.LogDescription | null) => log !== null
                 )
         }
-        return parsedLogs ?? null
+        return { txHash: hash, logs: parsedLogs }
```
Comment (Lisooo790926) [inline packages/relay/src/services/singletons/TransactionManager.ts:167]: Do you know what does this parseLogs use for ?

Comment (ryanycw) [reply packages/relay/src/services/singletons/TransactionManager.ts:167]: It's used to get logs from on-chain events

https://github.com/social-tw/social-tw-website/blob/3412f14af604c451ec26104d7ae34ad9da5c2a20/packages/relay/src/services/PostService.ts#L246

File: packages/relay/src/services/PostService.ts (hunk 1 above)
Comment (ryanycw) [reply packages/relay/src/services/PostService.ts:259]: Thank you for the suggestions. Would it be better that we keep the action count adjustment in Services? Since it will be more consistent, cause we won't be able to identify whether this transaction is using queueTx or executeTx. So readers won't be confused that some handle events have adjusted action count and some don't.

Comment (Lisooo790926) [reply packages/relay/src/services/PostService.ts:259]: Understood, but no matter queueTx or executeTx both should go through eventHandler, if we could put counter logic with insert, it will be easily to extend and develop in the future (could easily refer to other event method). Also, for consistency, if we keep all logic in eventHandler, I believe there is no different case for User Experience, for example, some services is using queueTx with counter, user will see counter increase immediately, but the others will be opposite.

File: packages/relay/src/db/schema.ts [hunk 3]
```diff
@@ -61,7 +61,11 @@ const _schema = [
             },
             // status 0: haven't found the post on-chain
             // status 1: found the post on-chain
-            ['status', 'Int'],
+            {
```
Comment (chentihe) [inline packages/relay/src/db/schema.ts:64]: since the post will be inserted into db by synchronizer, do we still need this column?

File: packages/relay/src/services/UserService.ts [hunk 4]
```diff
@@ -131,14 +131,13 @@ export class UserService {
             ]
         )
 
-        const parsedLogs = await TransactionManager.executeTransaction(
+        const { logs, txHash } = await TransactionManager.executeTransaction(
```
Comment (chentihe) [inline packages/relay/src/services/UserService.ts:134]: After modifing callContract method of TransactionManager, user sign up function can be modified to one line like this `TransactionManager.callContract('userSignUp',[signupProof.publicSignals, signupProof.proof, hashUserId, fromServer], TXEXECUTION.EXECUTE)`

**Review by chentihe — APPROVED** [review]
